/**
 * Site-wide constants for SEO / sitemap / canonical URLs.
 *
 * `SITE_URL` is read from the build-time environment variable
 * `NEXT_PUBLIC_SITE_URL` so that a custom production domain (e.g.
 * `https://temstream.cloud`) can override the Vercel preview domain without
 * code changes. Falls back to the custom production domain if unset.
 *
 * The fallback is intentionally `https://temstream.cloud` rather than the
 * Vercel preview domain: temstream-site.vercel.app is not reachable from
 * mainland China (Baidu/Bing-CN crawlers get timeouts and visitors get
 * blocked), so sitemap + OG + hreflang must point at the China-friendly
 * domain by default.
 */
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/+$/, '') ||
  'https://temstream.cloud';

/**
 * Site-wide identity constants used by global Schema.org payloads
 * (`Organization`, `WebSite`) and by the verification meta tags in
 * the root `<head>`. Centralizing these here keeps the JSON-LD
 * factories free of strings that don't have a single source of
 * truth.
 *
 * `SITE_NAME` is the brand name as it should appear in Google's
 * knowledge panel and in OpenGraph `siteName`. Keep it short — Google
 * truncates anything longer than ~50 characters.
 */
export const SITE_NAME = 'temstream';

/**
 * One-line description used as `description` on the global
 * `Organization` and `WebSite` JSON-LD payloads. Intentionally
 * locale-free: the root `Organization`/`WebSite` shapes are emitted
 * from the locale-less root layout, so this string should be a
 * neutral, bilingual-safe statement of what the site is. Pages
 * carry their own localized descriptions via `generateMetadata`.
 */
export const SITE_DESCRIPTION =
  'temstream is a Chinese-language guide to Moonlight + Sunshine — open-source, low-latency, self-hosted game streaming.';

/**
 * Absolute URL to the brand icon. Resolved against `SITE_URL` at
 * build time so Googlebot can fetch it for the knowledge panel.
 * `/icon` is generated by `app/icon.tsx` and served as a PNG by
 * the App Router; we also generate a 32x32 variant at `/favicon-32x32`
 * via the same pipeline.
 */
export const SITE_LOGO_PATH = '/icon';

/**
 * Locale list mirrored from `i18n/routing.ts`. We deliberately
 * redeclare it here rather than importing from the routing module:
 * the routing module is consumed by next-intl and pulls in
 * request-time code, while the JSON-LD factories in
 * `lib/jsonld-schemas.ts` are pure data and should be usable from
 * build scripts (e.g. `validate-jsonld.mjs`) that don't have a
 * request context.
 */
export const SITE_LOCALES = ['zh', 'en'] as const;
export type SiteLocale = (typeof SITE_LOCALES)[number];

/**
 * Locale-free pathname for every page that should appear in `sitemap.xml`
 * and in the `hreflang` map. The empty string `''` represents the locale
 * root, i.e. the home page.
 *
 * IMPORTANT: keep this list in sync with the routes under `app/[locale]/`.
 * Each entry corresponds to one URL per locale.
 */
export const SITE_PAGES = [
  '', // home
  '/wan',
  '/download',
  '/tutorial',
  '/faq',
  '/lan',
  '/lan-download',
  '/lan-tutorial',
  '/lan-faq',
] as const;

export type SitePath = (typeof SITE_PAGES)[number];